
const API=(()=>{const match=location.pathname.match(/\/plugins\/([^/]+)/);return '/v0/management/plugins/'+(match?decodeURIComponent(match[1]):'codex-health-monitor')})();
const SESSION_KEY='codex-health-monitor:admin-key';
const el=id=>document.getElementById(id);
let loadInFlight=false,historyRows=[],historyPage=1,historyPageSize=10,currentAccounts=[],savedSchedule=null,draftSchedule=null,scheduleData=null,dirty=false;
function decodeManagerStorage(value){if(!value||!value.startsWith('enc::v1::'))return value;try{const encoded=atob(value.slice(9));const key=new TextEncoder().encode('cli-proxy-api-webui::secure-storage|'+location.host+'|'+navigator.userAgent);const decoded=new Uint8Array(encoded.length);for(let i=0;i<encoded.length;i++)decoded[i]=encoded.charCodeAt(i)^key[i%key.length];return new TextDecoder().decode(decoded)}catch(_){return ''}}
function parseStored(value){let current=decodeManagerStorage(value);for(let i=0;i<3&&typeof current==='string';i++){try{current=JSON.parse(current)}catch(_){break}}return current}
function extractManagementKey(value){const parsed=parseStored(value);if(typeof parsed==='string')return parsed;if(!parsed||typeof parsed!=='object')return '';if(typeof parsed.managementKey==='string')return parsed.managementKey;if(parsed.state&&typeof parsed.state.managementKey==='string')return parsed.state.managementKey;if(typeof parsed.value==='string')return parsed.value;return ''}
function managementKey(){const sessionKey=sessionStorage.getItem(SESSION_KEY)||'';if(sessionKey)return sessionKey;for(const name of ['cli-proxy-auth','managementKey']){const key=extractManagementKey(localStorage.getItem(name)||'');if(key)return key}return ''}
async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};const key=managementKey();if(key)headers.Authorization='Bearer '+key;const response=await fetch(API+path,{...options,headers});let data={};try{data=await response.json()}catch(_){ }if(response.status===401){const error=new Error(data.error||data.message||'管理员密钥无效');error.auth=true;throw error}if(!response.ok)throw new Error(data.error||('HTTP '+response.status));return data}
function escapeHTML(value){return String(value??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))}
function dateText(value){if(!value||String(value).startsWith('0001-'))return '-';const date=new Date(value);return Number.isNaN(date.getTime())?'-':date.toLocaleString('zh-CN',{hour12:false})}
function statusLabel(value){const labels={healthy:'健康',unauthorized:'未授权',payment_required:'额度异常',forbidden:'账号被拒绝',rate_limited:'受限',upstream_error:'上游异常',network_error:'网络异常',timeout:'超时',response_error:'响应异常',credential_error:'凭证异常',request_error:'请求异常',unexpected_output:'输出异常',disabled:'已停用',not_checked:'未检测',checking:'检测中'};return labels[value]||value||'未知'}
function statusHTML(row){const cls=row.healthy?'healthy':(row.status==='checking'||row.status==='not_checked'?'checking':'bad');return '<span class="status '+cls+'"><span class="status-dot"></span>'+escapeHTML(statusLabel(row.status))+'</span>'}
function cooldownHTML(row){return (row.unavailable&&row.status!=='disabled')?'<span class="status neutral" title="CPA 临时不可用状态；仍允许独立健康探测"><span class="status-dot"></span>冷却中</span>':''}
function httpHTML(status){const value=Number(status)||0;if(!value)return '<span class="http">-</span>';return '<span class="http '+(value>=200&&value<300?'ok':'fail')+'">'+value+'</span>'}
function latencyText(value){const latency=Number(value)||0;return latency>0?latency.toLocaleString('zh-CN')+' ms':'-'}
function emptyHTML(columns,message){return '<tr><td colspan="'+columns+'" class="empty">'+escapeHTML(message)+'</td></tr>'}
function showNotice(message,isError=false){el('noticeText').textContent=message;el('noticeIcon').setAttribute('href',isError?'#i-alert':'#i-check');el('notice').className='notice show'+(isError?' error-notice':'');clearTimeout(window.noticeTimer);window.noticeTimer=setTimeout(()=>el('notice').className='notice',3200)}
function requestAdminKey(message){if(message)showNotice(message,true);el('authOverlay').classList.add('show');setTimeout(()=>el('adminKey').focus(),0)}
function setConnection(state){el('connection').className='chip '+state;el('connectionLabel').textContent=state==='online'?'已连接':state==='offline'?'连接失败':'连接中'}
function setButtonLoading(button,loading,labelNode,loadingLabel,readyLabel,readyIcon){button.disabled=loading;button.classList.toggle('is-loading',loading);const use=button.querySelector('use');if(use&&readyIcon)use.setAttribute('href',loading?'#i-loader':readyIcon);if(labelNode)labelNode.textContent=loading?loadingLabel:readyLabel}
function handleActionError(error){if(error.auth)requestAdminKey(error.message);else showNotice(error.message,true)}
function clone(v){return JSON.parse(JSON.stringify(v||{}))}
function excludedSet(){return new Set(String(draftSchedule?.excluded_emails||'').split(',').map(v=>v.trim().toLowerCase()).filter(Boolean))}
function accountSelectionKey(account){return String(account.selection_key||account.email||('@auth:'+String(account.auth_index||''))).trim().toLowerCase()}
function markDirty(){dirty=true;el('selectionDirty').classList.add('show');el('simDirty').classList.add('show')}
function clearDirty(){dirty=false;el('selectionDirty').classList.remove('show');el('simDirty').classList.remove('show')}
function renderAccounts(accounts){currentAccounts=accounts.map(a=>({...a}));const excluded=excludedSet();for(const account of currentAccounts)account.selected=!excluded.has(accountSelectionKey(account));const selected=currentAccounts.filter(a=>a.selected).length;el('accountsMeta').textContent=currentAccounts.length+' 个 Codex 账号（已选择 '+selected+' 个；新账号默认生效）';el('summaryAccounts').textContent=selected+' 个';el('accounts').innerHTML=currentAccounts.length?currentAccounts.map(account=>{const email=account.email||'-',avatar=email==='-'?'?':email.trim().charAt(0);return '<tr><td class="select-cell"><input class="account-check" type="checkbox" data-key="'+escapeHTML(accountSelectionKey(account))+'" '+(account.selected?'checked':'')+' aria-label="'+escapeHTML(email)+' 生效"></td><td><div class="account"><span class="avatar">'+escapeHTML(avatar)+'</span><span class="account-email">'+escapeHTML(email)+'</span></div></td><td><span class="mono">'+escapeHTML(account.auth_index||'-')+'</span></td><td><span class="mono">'+escapeHTML(account.account_id||'-')+'</span></td><td>'+statusHTML(account)+cooldownHTML(account)+'</td><td>'+httpHTML(account.http_status)+'</td><td>'+latencyText(account.latency_ms)+'</td><td class="date">'+dateText(account.checked_at)+'</td><td><span class="error" title="'+escapeHTML(account.error_message||'')+'">'+escapeHTML(account.error_message||'-')+'</span></td></tr>'}).join(''):emptyHTML(9,'没有 Codex 账号')}
function applySelectionFromDOM(){const unchecked=[];document.querySelectorAll('.account-check').forEach(box=>{const account=currentAccounts.find(a=>accountSelectionKey(a)===box.dataset.key);if(account)account.selected=box.checked;if(!box.checked)unchecked.push(String(box.dataset.key||'').toLowerCase())});draftSchedule.excluded_emails=unchecked.sort().join(',');el('summaryAccounts').textContent=currentAccounts.filter(a=>a.selected).length+' 个';el('accountsMeta').textContent=currentAccounts.length+' 个 Codex 账号（已选择 '+currentAccounts.filter(a=>a.selected).length+' 个；新账号默认生效）';markDirty()}
function triggerLabel(value){return ({manual:'手动',scheduled:'定时',interval:'按间隔',daily_times:'固定时间',window_optimized:'窗口优化',quota_retry:'额度补偿',window_retry:'补偿重试'})[value]||value||'定时'}
