function applyFullWidthLayout(){const workspace=document.querySelector('.workspace'),stack=document.querySelector('.left-stack'),simulator=document.querySelector('.simulator'),schedule=document.querySelector('.schedule-panel');if(!workspace||!stack||!simulator||!schedule)return;workspace.style.display='block';stack.style.display='grid';stack.style.gridTemplateColumns='1fr';stack.style.gap='14px';stack.style.marginBottom='0';simulator.id='windowSimulator';simulator.style.border='0';simulator.style.borderTop='1px solid var(--line)';simulator.style.borderRadius='0';simulator.style.boxShadow='none';simulator.style.margin='0';simulator.style.display='none';if(simulator.parentElement!==schedule)schedule.appendChild(simulator)}
function applyQuotaTableLayout(){const tbody=el('accounts'),table=tbody&&tbody.closest?tbody.closest('table'):null,headRow=table&&table.querySelector?table.querySelector('thead tr'):null;if(table)table.classList.add('accounts-quota-table');if(headRow&&!headRow.querySelector('[data-quota-column]')){const headers=[...headRow.querySelectorAll('th')],statusHeader=headers[4];if(statusHeader){const quotaHeader=document.createElement('th'),resetHeader=document.createElement('th');quotaHeader.textContent='额度信息';quotaHeader.dataset.quotaColumn='quota';resetHeader.textContent='重置信息';resetHeader.dataset.quotaColumn='reset';statusHeader.parentNode.insertBefore(quotaHeader,statusHeader.nextSibling);quotaHeader.parentNode.insertBefore(resetHeader,quotaHeader.nextSibling)}}const empty=tbody&&tbody.querySelector?tbody.querySelector('td.empty'):null;if(empty)empty.colSpan=11;if(!document.getElementById('quotaColumnStyles')){const style=document.createElement('style');style.id='quotaColumnStyles';style.textContent='.accounts-quota-table{min-width:1340px}.quota-cell{min-width:270px}.reset-cell{min-width:120px}.quota-stack{display:grid;gap:7px;min-width:250px}.quota-row{display:grid;grid-template-columns:28px minmax(82px,1fr) 38px 82px;gap:6px;align-items:center;white-space:nowrap}.quota-label{font:760 11px/1 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;color:#45566d}.quota-bar{height:7px;border-radius:999px;background:#e8edf3;overflow:hidden}.quota-bar-fill{display:block;height:100%;border-radius:inherit}.quota-bar-fill.good{background:#0ba66b}.quota-bar-fill.warn{background:#d69212}.quota-bar-fill.danger{background:#e43838}.quota-pct{font-size:11px;text-align:right}.quota-reset,.reset-stack,.reset-count{font-size:11px;color:#607086}.reset-stack{display:grid;gap:5px;white-space:nowrap}.quota-empty{color:#9aa6b5}.accounts-quota-table th[data-quota-column="quota"]{min-width:270px}.accounts-quota-table th[data-quota-column="reset"]{min-width:120px}';document.head.appendChild(style)}}
function syncWindowSaveState(){const button=el('saveWindow');if(button)button.disabled=!dirty}
function markDirty(){dirty=true;el('selectionDirty').classList.add('show');el('simDirty').classList.add('show');syncWindowSaveState()}
function clearDirty(){dirty=false;el('selectionDirty').classList.remove('show');el('simDirty').classList.remove('show');syncWindowSaveState()}
function renderSimulator(){const s=scheduleFromUI(true),ws=timeMin(s.work_start),ls=timeMin(s.lunch_start),le=timeMin(s.lunch_end),we=timeMin(s.work_end),anchor=timeMin(s.anchor_time),rec=recommendAnchorJS(s),work=(ls-ws)+(we-le),a=simulateAvailability(s,ws),b=simulateAvailability(s,anchor),gain=b-a,window=Number(s.window_hours)*60;el('workDuration').textContent=durationText(work);el('workDurationDetail').textContent=s.work_start+'–'+s.work_end+'，扣除午休 '+durationText(le-ls);el('strategyAMetric').textContent=durationText(a);el('strategyBMetric').textContent=durationText(b);el('gainMetric').textContent=(gain>=0?'+':'')+durationText(Math.abs(gain));el('strategyAValue').textContent=durationText(a);el('strategyBValue').textContent=durationText(b);el('strategyABar').style.width=Math.min(100,a/Math.max(work,1)*100)+'%';el('strategyBBar').style.width=Math.min(100,b/Math.max(work,1)*100)+'%';el('bestRange').textContent=clock(rec.start)+'–'+clock(rec.end);el('recommendedAnchor').textContent=clock(rec.recommended);const points=[];for(let p=anchor;p<we;p+=window)points.push(p);el('estimatedPoints').textContent='预计窗口点：'+points.map(clock).join(' / ')+'（每账号实际 +0–3 分钟）';el('windowStrip').innerHTML=points.map((p,i)=>'<div class="window-pill">窗口 '+(i+1)+'<br>'+escapeHTML(windowRangeText(p,p+window))+'</div>').join('');const start=0,end=1440;el('timelineAxis').innerHTML='';for(let h=0;h<=24;h++){const pos=h/24*100;el('timelineAxis').innerHTML+='<span class="axis-label" style="left:'+pos+'%">'+String(h).padStart(2,'0')+':00</span>'}renderTrack('trackA',s,ws,'a',start,end);renderTrack('trackB',s,anchor,'b',start,end);renderWindowSummary()}
async function persistSchedule(payload,message){const data=await api('/schedule',{method:'POST',body:JSON.stringify(payload)});savedSchedule=clone(data.schedule||payload);draftSchedule=clone(savedSchedule);scheduleData=data;el('nextRunFull').textContent=data.next_run_at?dateText(data.next_run_at):'未安排';clearDirty();showNotice(message);return data}
async function load(){if(loadInFlight)return;loadInFlight=true;clearTimeout(window.pollTimer);setConnection('');setButtonLoading(el('refresh'),true,null,'','','#i-refresh');try{const [status,accounts,history,schedule,quotaFiles]=await Promise.all([api('/status'),api('/accounts'),api('/history'),api('/schedule'),loadQuotaAuthFiles()]);el('authOverlay').classList.remove('show');setConnection('online');renderSchedule(schedule);renderAccounts(mergeQuotaAccounts(accounts.accounts||[],quotaFiles));renderHistory(history.history||[]);renderSimulator();setButtonLoading(el('run'),!!status.running,el('runLabel'),'检测中','立即检测','#i-play');if(status.running)window.pollTimer=setTimeout(load,1800)}catch(error){setConnection('offline');handleActionError(error)}finally{loadInFlight=false;setButtonLoading(el('refresh'),false,null,'','','#i-refresh')}}

document.querySelectorAll('input[name="scheduleMode"]').forEach(node=>node.addEventListener('change',()=>{toggleMode();markDirty()}));
el('accounts').addEventListener('change',event=>{if(event.target.classList.contains('account-check'))applySelectionFromDOM()});
el('selectAll').addEventListener('click',()=>{document.querySelectorAll('.account-check').forEach(n=>n.checked=true);applySelectionFromDOM()});el('selectNone').addEventListener('click',()=>{document.querySelectorAll('.account-check').forEach(n=>n.checked=false);applySelectionFromDOM()});
el('refresh').addEventListener('click',load);el('historyPrev').addEventListener('click',()=>{historyPage--;renderHistoryPage()});el('historyNext').addEventListener('click',()=>{historyPage++;renderHistoryPage()});el('historyPageSize').addEventListener('change',()=>{historyPageSize=Number(el('historyPageSize').value);historyPage=1;renderHistoryPage()});
async function runNow(){setButtonLoading(el('run'),true,el('runLabel'),'检测中','立即检测','#i-play');try{await api('/run',{method:'POST',body:'{}'});showNotice('检测已启动');await load()}catch(error){handleActionError(error)}finally{setButtonLoading(el('run'),false,el('runLabel'),'检测中','立即检测','#i-play')}}el('run').addEventListener('click',runNow);el('scheduleRun').addEventListener('click',runNow);
el('scheduleForm').addEventListener('submit',async event=>{event.preventDefault();const payload=scheduleFromUI(false);el('saveSchedule').disabled=true;try{const data=await persistSchedule(payload,'检测计划已保存');renderSchedule(data);renderAccounts(currentAccounts);renderSimulator()}catch(error){handleActionError(error)}finally{el('saveSchedule').disabled=false}});
const simulatorInputChanged=()=>{markDirty();renderSimulator()};for(const id of ['windowHours','quotaMinutes','workStart','lunchStart','lunchEnd','workEnd','simTimezone','healthThreshold','anchorTime']){const node=el(id);node.addEventListener('input',simulatorInputChanged);node.addEventListener('change',simulatorInputChanged)}document.querySelectorAll('#weekdayToggles input').forEach(n=>n.addEventListener('change',()=>{markDirty();renderSimulator()}));
el('recalculate').addEventListener('click',()=>{const s=scheduleFromUI(true),rec=recommendAnchorJS(s);el('anchorTime').value=clock(rec.recommended);markDirty();renderSimulator()});
el('undoChanges').addEventListener('click',()=>{draftSchedule=clone(savedSchedule);renderAccounts(currentAccounts.map(a=>({...a})));fillSimulator(draftSchedule);const radio=document.querySelector('input[name="scheduleMode"][value="'+(draftSchedule.schedule_mode||'window_optimized')+'"]');if(radio)radio.checked=true;el('intervalMin').value=draftSchedule.interval_min||30;el('dailyTimes').value=draftSchedule.daily_times||'';el('timezone').value=draftSchedule.timezone||'Asia/Shanghai';el('timeoutSec').value=draftSchedule.timeout_sec||30;toggleMode();clearDirty();showNotice('已撤销未保存修改')});
el('saveWindow').addEventListener('click',async()=>{const payload=scheduleFromUI(true);const radio=document.querySelector('input[name="scheduleMode"][value="window_optimized"]');if(radio)radio.checked=true;toggleMode();el('saveWindow').disabled=true;try{const data=await persistSchedule(payload,'窗口优化配置已保存并生效');renderSchedule(data);renderAccounts(currentAccounts);renderSimulator()}catch(error){handleActionError(error)}finally{el('saveWindow').disabled=!dirty}});
el('timezone').addEventListener('input',()=>{if(selectedMode()==='window_optimized'){el('simTimezone').value=el('timezone').value;markDirty();renderSimulator()}});
el('authForm').addEventListener('submit',event=>{event.preventDefault();const key=el('adminKey').value.trim();if(!key)return;sessionStorage.setItem(SESSION_KEY,key);el('adminKey').value='';load()});
applyQuotaTableLayout();applyFullWidthLayout();clearDirty();load();
