
const API=(()=>{const match=location.pathname.match(/\/plugins\/([^/]+)/);return '/v0/management/plugins/'+(match?decodeURIComponent(match[1]):'codex-health-monitor')})();
const MANAGEMENT_API='/v0/management';
const SESSION_KEY='codex-health-monitor:admin-key';
const el=id=>document.getElementById(id);
let loadInFlight=false,historyRows=[],historyPage=1,historyPageSize=10,currentAccounts=[],savedSchedule=null,draftSchedule=null,scheduleData=null,dirty=false;
function decodeManagerStorage(value){if(!value||!value.startsWith('enc::v1::'))return value;try{const encoded=atob(value.slice(9));const key=new TextEncoder().encode('cli-proxy-api-webui::secure-storage|'+location.host+'|'+navigator.userAgent);const decoded=new Uint8Array(encoded.length);for(let i=0;i<encoded.length;i++)decoded[i]=encoded.charCodeAt(i)^key[i%key.length];return new TextDecoder().decode(decoded)}catch(_){return ''}}
function parseStored(value){let current=decodeManagerStorage(value);for(let i=0;i<3&&typeof current==='string';i++){try{current=JSON.parse(current)}catch(_){break}}return current}
function extractManagementKey(value){const parsed=parseStored(value);if(typeof parsed==='string')return parsed;if(!parsed||typeof parsed!=='object')return '';if(typeof parsed.managementKey==='string')return parsed.managementKey;if(parsed.state&&typeof parsed.state.managementKey==='string')return parsed.state.managementKey;if(typeof parsed.value==='string')return parsed.value;return ''}
function managementKey(){const sessionKey=sessionStorage.getItem(SESSION_KEY)||'';if(sessionKey)return sessionKey;for(const name of ['cli-proxy-auth','managementKey']){const key=extractManagementKey(localStorage.getItem(name)||'');if(key)return key}return ''}
async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};const key=managementKey();if(key)headers.Authorization='Bearer '+key;const response=await fetch(API+path,{...options,headers});let data={};try{data=await response.json()}catch(_){ }if(response.status===401){const error=new Error(data.error||data.message||'管理员密钥无效');error.auth=true;throw error}if(!response.ok)throw new Error(data.error||('HTTP '+response.status));return data}
async function managementApi(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};const key=managementKey();if(key)headers.Authorization='Bearer '+key;const response=await fetch(MANAGEMENT_API+path,{...options,headers});let data={};try{data=await response.json()}catch(_){ }if(!response.ok)throw new Error(data.error||data.message||('HTTP '+response.status));return data}
async function loadQuotaAuthFiles(){try{const data=await managementApi('/auth-files');return Array.isArray(data.files)?data.files:[]}catch(_){return []}}
function escapeHTML(value){return String(value??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))}
function dateText(value){if(!value||String(value).startsWith('0001-'))return '-';const date=new Date(value);return Number.isNaN(date.getTime())?'-':date.toLocaleString('zh-CN',{hour12:false})}
function shortDateText(value){if(value===null||value===undefined||value==='')return '--';const date=value instanceof Date?value:new Date(value);if(Number.isNaN(date.getTime()))return '--';const p=n=>String(n).padStart(2,'0');return p(date.getMonth()+1)+'/'+p(date.getDate())+' '+p(date.getHours())+':'+p(date.getMinutes())}
function statusLabel(value){const labels={healthy:'健康',unauthorized:'未授权',payment_required:'额度异常',forbidden:'账号被拒绝',rate_limited:'受限',upstream_error:'上游异常',network_error:'网络异常',timeout:'超时',response_error:'响应异常',credential_error:'凭证异常',request_error:'请求异常',unexpected_output:'输出异常',disabled:'已停用',not_checked:'未检测',checking:'检测中'};return labels[value]||value||'未知'}
function statusHTML(row){const cls=row.healthy?'healthy':(row.status==='checking'||row.status==='not_checked'?'checking':'bad');return '<span class="status '+cls+'"><span class="status-dot"></span>'+escapeHTML(statusLabel(row.status))+'</span>'}
function cooldownHTML(row){return (row.unavailable&&row.status!=='disabled')?'<span class="status neutral" title="CPA 临时不可用状态；仍允许独立健康探测"><span class="status-dot"></span>冷却中</span>':''}
function httpHTML(status){const value=Number(status)||0;if(!value)return '<span class="http">-</span>';return '<span class="http '+(value>=200&&value<300?'ok':'fail')+'">'+value+'</span>'}
function latencyText(value){const latency=Number(value)||0;return latency>0?latency.toLocaleString('zh-CN')+' ms':'-'}
function emptyHTML(columns,message){return '<tr><td colspan="'+columns+'" class="empty">'+escapeHTML(message)+'</td></tr>'}
function showNotice(message,isError=false){el('noticeText').textContent=message;el('noticeIcon').setAttribute('href',isError?'#i-alert':'#i-check');el('notice').className='notice show'+(isError?' error-notice':'');clearTimeout(window.noticeTimer);window.noticeTimer=setTimeout(()=>el('notice').className='notice',3200)}
function requestAdminKey(message){if(message)showNotice(message,true);el('authOverlay').classList.add('show');setTimeout(()=>el('adminKey').focus(),0)}
function setConnection(state){el('connection').className='chip '+state;el('connectionLabel').textContent=state==='online'?'已连接':state==='offline'?'连接失败':'连接中'}
function setButtonLoading(button,loading,labelNode,loadingLabel,readyLabel,readyIcon){button.disabled=loading;button.classList.toggle('is-loading',loading);const use=button.querySelector('use');if(use&&readyIcon)use.setAttribute('href',loading?'#i-loader':readyIcon);if(labelNode)labelNode.textContent=loading?loadingLabel:readyLabel}
function handleActionError(error){if(error.auth)requestAdminKey(error.message);else showNotice(error.message,true)}
function clone(v){return JSON.parse(JSON.stringify(v||{}))}
function excludedSet(){return new Set(String(draftSchedule?.excluded_emails||'').split(',').map(v=>v.trim().toLowerCase()).filter(Boolean))}
function accountSelectionKey(account){return String(account.selection_key||account.email||('@auth:'+String(account.auth_index||''))).trim().toLowerCase()}
function markDirty(){dirty=true;el('selectionDirty').classList.add('show');el('simDirty').classList.add('show')}
function clearDirty(){dirty=false;el('selectionDirty').classList.remove('show');el('simDirty').classList.remove('show')}
function signalMap(entry){const raw=entry&&entry.quota&&entry.quota.signals;const result={};if(!raw||typeof raw!=='object')return result;for(const [key,value] of Object.entries(raw)){result[String(key).trim().toLowerCase()]=String(value??'').trim()}return result}
function epochMillis(value){if(value===null||value===undefined||value==='')return null;if(typeof value==='number'&&Number.isFinite(value))return value>1e12?value:value*1000;const raw=String(value).trim();if(/^\d+(?:\.\d+)?$/.test(raw)){const n=Number(raw);return Number.isFinite(n)?(n>1e12?n:n*1000):null}const parsed=Date.parse(raw);return Number.isNaN(parsed)?null:parsed}
function quotaDurationLabel(minutes){const value=Math.round(Number(minutes)||0);if(value<=0)return '-';if(value%10080===0)return (value/10080*7)+'D';if(value%1440===0)return (value/1440)+'D';if(value%60===0)return (value/60)+'H';return value+'m'}
function collectQuotaWindows(entry){const signals=signalMap(entry),groups=new Map(),fields='used-percent|window-minutes|reset-after-seconds|reset-at';for(const [name,value] of Object.entries(signals)){let match=new RegExp('^x-codex-(primary|secondary)-('+fields+')$').exec(name),namespace='base',lane,field;if(match){lane=match[1];field=match[2]}else{match=new RegExp('^x-codex-(.+)-(primary|secondary)-('+fields+')$').exec(name);if(!match)continue;namespace=match[1];lane=match[2];field=match[3]}const key=namespace+'|'+lane;if(!groups.has(key))groups.set(key,{namespace,lane});groups.get(key)[field]=value}const observedAt=epochMillis(entry?.quota?.observed_at),out=[];for(const group of groups.values()){const minutes=Number(group['window-minutes']),used=Number(group['used-percent']);if(!Number.isFinite(minutes)||minutes<=0||!Number.isFinite(used))continue;let resetAt=epochMillis(group['reset-at']);if(resetAt===null){const after=Number(group['reset-after-seconds']);if(Number.isFinite(after)&&after>=0)resetAt=(observedAt??Date.now())+after*1000}out.push({minutes,used:Math.max(0,Math.min(100,used)),remaining:Math.max(0,Math.min(100,100-used)),resetAt,namespace:group.namespace,lane:group.lane,rank:group.namespace==='base'?0:(group.namespace.startsWith('additional-')?2:1)})}out.sort((a,b)=>a.rank-b.rank||a.minutes-b.minutes||a.lane.localeCompare(b.lane));return out}
function quotaWindowsForEntry(entry){const all=collectQuotaWindows(entry),chosen=[];for(const target of [300,10080]){const found=all.find(item=>Math.abs(item.minutes-target)<=Math.max(1,target*.01)&&!chosen.includes(item));if(found)chosen.push(found)}for(const item of all){if(chosen.length>=2)break;if(chosen.some(existing=>Math.abs(existing.minutes-item.minutes)<1))continue;chosen.push(item)}return chosen.slice(0,2)}
function quotaTone(remaining){return remaining<=20?'danger':remaining<=50?'warn':'good'}
function quotaInfoHTML(entry){const windows=quotaWindowsForEntry(entry);if(!windows.length)return '<span class="quota-empty">--</span>';const observed=entry?.quota?.observed_at?dateText(entry.quota.observed_at):'';return '<div class="quota-stack"'+(observed?' title="额度快照观测于 '+escapeHTML(observed)+'"':'')+'>'+windows.map(window=>{const pct=Math.round(window.remaining),tone=quotaTone(window.remaining);return '<div class="quota-row"><span class="quota-label">'+escapeHTML(quotaDurationLabel(window.minutes))+'</span><span class="quota-bar"><span class="quota-bar-fill '+tone+'" style="width:'+window.remaining.toFixed(2)+'%"></span></span><strong class="quota-pct">'+pct+'%</strong><span class="quota-reset">'+escapeHTML(shortDateText(window.resetAt))+'</span></div>'}).join('')+'</div>'}
function resetInfo(entry){const quota=entry&&entry.quota&&typeof entry.quota==='object'?entry.quota:{},expiries=[];const credits=Array.isArray(quota.reset_credits)?quota.reset_credits:(Array.isArray(quota.resetCredits)?quota.resetCredits:[]);for(const item of credits){const value=item&&typeof item==='object'?(item.expires_at_ms??item.expiresAtMs??item.expires_at??item.expiresAt):item,ms=epochMillis(value);if(ms!==null)expiries.push(ms)}const signals=signalMap(entry);for(const [name,value] of Object.entries(signals)){if(!/(reset[-_]?credits?|credits?.*reset)/i.test(name)||!/(expire|expiry|expires)/i.test(name))continue;for(const part of String(value).split(/[;,]/)){const ms=epochMillis(part.trim());if(ms!==null)expiries.push(ms)}}const unique=[...new Set(expiries)].sort((a,b)=>a-b);let count=null;for(const candidate of [quota.reset_credits_available,quota.resetCreditsAvailable,signals['x-codex-reset-credits-available'],signals['x-codex-credits-reset-available']]){if(candidate===undefined||candidate===null||candidate==='')continue;const n=Number(candidate);if(Number.isFinite(n)){count=n;break}}return {expiries:unique,count}}
function resetInfoHTML(entry){const info=resetInfo(entry);if(info.expiries.length)return '<div class="reset-stack">'+info.expiries.map(value=>'<span>'+escapeHTML(shortDateText(value))+'</span>').join('')+'</div>';if(info.count!==null)return '<span class="reset-count">'+escapeHTML(String(info.count))+' 次</span>';return '<span class="quota-empty">--</span>'}
function mergeQuotaAccounts(accounts,files){const byIndex=new Map();for(const file of files||[]){if(String(file?.provider||file?.type||'').toLowerCase()!=='codex')continue;const index=String(file?.auth_index||'').trim();if(index)byIndex.set(index,file)}return (accounts||[]).map(account=>({...account,quota_entry:byIndex.get(String(account?.auth_index||'').trim())||null}))}
function renderAccounts(accounts){currentAccounts=accounts.map(a=>({...a}));const excluded=excludedSet();for(const account of currentAccounts)account.selected=!excluded.has(accountSelectionKey(account));const selected=currentAccounts.filter(a=>a.selected).length;el('accountsMeta').textContent=currentAccounts.length+' 个 Codex 账号（已选择 '+selected+' 个；新账号默认生效）';el('summaryAccounts').textContent=selected+' 个';el('accounts').innerHTML=currentAccounts.length?currentAccounts.map(account=>{const email=account.email||'-',avatar=email==='-'?'?':email.trim().charAt(0);return '<tr><td class="select-cell"><input class="account-check" type="checkbox" data-key="'+escapeHTML(accountSelectionKey(account))+'" '+(account.selected?'checked':'')+' aria-label="'+escapeHTML(email)+' 生效"></td><td><div class="account"><span class="avatar">'+escapeHTML(avatar)+'</span><span class="account-email">'+escapeHTML(email)+'</span></div></td><td><span class="mono">'+escapeHTML(account.auth_index||'-')+'</span></td><td><span class="mono">'+escapeHTML(account.account_id||'-')+'</span></td><td>'+statusHTML(account)+cooldownHTML(account)+'</td><td class="quota-cell">'+quotaInfoHTML(account.quota_entry)+'</td><td class="reset-cell">'+resetInfoHTML(account.quota_entry)+'</td><td>'+httpHTML(account.http_status)+'</td><td>'+latencyText(account.latency_ms)+'</td><td class="date">'+dateText(account.checked_at)+'</td><td><span class="error" title="'+escapeHTML(account.error_message||'')+'">'+escapeHTML(account.error_message||'-')+'</span></td></tr>'}).join(''):emptyHTML(11,'没有 Codex 账号')}
function applySelectionFromDOM(){const unchecked=[];document.querySelectorAll('.account-check').forEach(box=>{const account=currentAccounts.find(a=>accountSelectionKey(a)===box.dataset.key);if(account)account.selected=box.checked;if(!box.checked)unchecked.push(String(box.dataset.key||'').toLowerCase())});draftSchedule.excluded_emails=unchecked.sort().join(',');el('summaryAccounts').textContent=currentAccounts.filter(a=>a.selected).length+' 个';el('accountsMeta').textContent=currentAccounts.length+' 个 Codex 账号（已选择 '+currentAccounts.filter(a=>a.selected).length+' 个；新账号默认生效）';markDirty()}
function triggerLabel(value){return ({manual:'手动',scheduled:'定时',interval:'按间隔',daily_times:'固定时间',window_optimized:'窗口优化',quota_retry:'额度补偿',window_retry:'补偿重试'})[value]||value||'定时'}
