function applyFullWidthLayout(){const workspace=document.querySelector('.workspace'),stack=document.querySelector('.left-stack'),simulator=document.querySelector('.simulator'),schedule=document.querySelector('.schedule-panel');if(!workspace||!stack||!simulator||!schedule)return;workspace.style.display='block';stack.style.display='grid';stack.style.gridTemplateColumns='1fr';stack.style.gap='14px';stack.style.marginBottom='0';simulator.id='windowSimulator';simulator.style.border='0';simulator.style.borderTop='1px solid var(--line)';simulator.style.borderRadius='0';simulator.style.boxShadow='none';simulator.style.margin='0';simulator.style.display='none';if(simulator.parentElement!==schedule)schedule.appendChild(simulator)}

const CODEX_USAGE_URL='https://chatgpt.com/backend-api/wham/usage';
const CODEX_RESET_CREDITS_URL='https://chatgpt.com/backend-api/wham/rate-limit-reset-credits';
const CODEX_RESET_CREDITS_CONSUME_URL='https://chatgpt.com/backend-api/wham/rate-limit-reset-credits/consume';
const CODEX_REQUEST_HEADERS={Authorization:'Bearer $TOKEN$','Content-Type':'application/json','User-Agent':'codex-tui/0.149.1 (Mac OS 26.5.2; arm64) iTerm.app/3.6.11 (codex-tui; 0.149.1)'};
const quotaCache=new Map(),quotaLoading=new Set(),quotaResetting=new Set();
let quotaCacheScope=null,quotaRefreshAllRunning=false;

function normalizeAuthIndex(value){return String(value||'').trim()}
function quotaAccountDisabled(account){return account?.disabled===true||account?.status==='disabled'}
function syncQuotaCacheScope(){const scope=managementKey()||'';if(scope===quotaCacheScope)return;quotaCacheScope=scope;quotaCache.clear();quotaLoading.clear();quotaResetting.clear()}
function pruneQuotaCache(accounts){const keep=new Set((accounts||[]).map(account=>normalizeAuthIndex(account?.auth_index)).filter(Boolean));for(const key of quotaCache.keys())if(!keep.has(key))quotaCache.delete(key);for(const key of quotaLoading)if(!keep.has(key))quotaLoading.delete(key);for(const key of quotaResetting)if(!keep.has(key))quotaResetting.delete(key)}
function quotaStateForAccount(account){const key=normalizeAuthIndex(account?.auth_index);return key?quotaCache.get(key):undefined}
function accountByAuthIndex(value){const key=normalizeAuthIndex(value);return currentAccounts.find(account=>normalizeAuthIndex(account?.auth_index)===key)}
function numericValue(value){if(value===null||value===undefined||value==='')return null;const number=Number(value);return Number.isFinite(number)?number:null}
function objectValue(value){return value&&typeof value==='object'&&!Array.isArray(value)?value:null}
function parseApiCallBody(result){const raw=result?.body;if(raw&&typeof raw==='object')return raw;if(typeof raw!=='string'||!raw.trim())return {};try{return JSON.parse(raw)}catch(_){throw new Error('上游返回了无法解析的额度数据')}}
function apiCallErrorDetail(result){const raw=result?.body;if(typeof raw!=='string'||!raw.trim())return '';try{const parsed=JSON.parse(raw);return String(parsed?.error?.message||parsed?.error||parsed?.message||'').trim()}catch(_){return raw.trim().slice(0,180)}}
async function codexManagementCall(account,method,url,extraHeaders={},data){const authIndex=normalizeAuthIndex(account?.auth_index);if(!authIndex)throw new Error('缺少 auth_index，无法刷新额度');const header={...CODEX_REQUEST_HEADERS,...extraHeaders};const accountId=String(account?.account_id||'').trim();if(accountId)header['Chatgpt-Account-Id']=accountId;const payload={auth_index:authIndex,method,url,header};if(data!==undefined)payload.data=typeof data==='string'?data:JSON.stringify(data);const result=await managementApi('/api-call',{method:'POST',body:JSON.stringify(payload)});const status=Number(result?.status_code||0);if(status<200||status>=300){const detail=apiCallErrorDetail(result);const error=new Error('额度接口 HTTP '+(status||'-')+(detail?' · '+detail:''));error.httpStatus=status;throw error}return parseApiCallBody(result)}
function resetAtFromWindow(window,fetchedAt){const record=objectValue(window);if(!record)return null;const direct=epochMillis(record.reset_at??record.resetAt);if(direct!==null)return direct;const after=numericValue(record.reset_after_seconds??record.resetAfterSeconds);return after!==null&&after>=0?fetchedAt+after*1000:null}
function codexQuotaWindowsFromUsage(payload,fetchedAt=Date.now()){const root=objectValue(payload)||{},rate=objectValue(root.rate_limit??root.rateLimit)||{},primary=objectValue(rate.primary_window??rate.primaryWindow),secondary=objectValue(rate.secondary_window??rate.secondaryWindow),raw=[primary,secondary].filter(Boolean);const secondsOf=window=>numericValue(window?.limit_window_seconds??window?.limitWindowSeconds);const monthly=window=>{const seconds=secondsOf(window);return seconds!==null&&seconds>=28*86400&&seconds<=31*86400};let five=raw.find(window=>secondsOf(window)===18000)||null,secondaryLong=raw.find(window=>secondsOf(window)===604800||monthly(window))||null;if(!five)five=primary&&primary!==secondaryLong?primary:null;if(!secondaryLong)secondaryLong=secondary&&secondary!==five?secondary:null;const limitReached=Boolean(rate.limit_reached??rate.limitReached)||rate.allowed===false;const make=(window,fallbackMinutes)=>{if(!window)return null;const seconds=secondsOf(window),minutes=seconds&&seconds>0?seconds/60:fallbackMinutes;let used=numericValue(window.used_percent??window.usedPercent);const resetAt=resetAtFromWindow(window,fetchedAt);if(used===null&&limitReached&&resetAt!==null)used=100;if(used===null)return null;used=Math.max(0,Math.min(100,used));return {minutes,used,remaining:Math.max(0,Math.min(100,100-used)),resetAt}};const out=[];const fiveWindow=make(five,300),longWindow=make(secondaryLong,10080);if(fiveWindow)out.push(fiveWindow);if(longWindow&&(!fiveWindow||Math.round(longWindow.minutes)!==Math.round(fiveWindow.minutes)))out.push(longWindow);return out.slice(0,2)}
function normalizeCodexResetCredits(payload){let value=payload;if(typeof value==='string'){try{value=JSON.parse(value)}catch(_){return {availableCount:null,applicableAvailableCount:null,credits:[],invalid:true}}}const record=objectValue(value);if(!record)return {availableCount:null,applicableAvailableCount:null,credits:[],invalid:true};const hasShape='credits'in record||'available_count'in record||'availableCount'in record||'applicable_available_count'in record||'applicableAvailableCount'in record;const credits=Array.isArray(record.credits)?record.credits.map(item=>{const credit=objectValue(item);if(!credit)return null;const resetType=String(credit.reset_type??credit.resetType??'').trim(),status=String(credit.status??'').trim(),expiresAt=credit.expires_at??credit.expiresAt;if(resetType!=='codex_rate_limits'||status!=='available'||!expiresAt)return null;return {id:String(credit.id||''),expiresAt:String(expiresAt),expiresAtMs:epochMillis(expiresAt)}}).filter(Boolean):[];return {availableCount:numericValue(record.available_count??record.availableCount),applicableAvailableCount:numericValue(record.applicable_available_count??record.applicableAvailableCount),credits,invalid:!hasShape}}
async function fetchCodexQuota(account){const fetchedAt=Date.now();const usage=await codexManagementCall(account,'GET',CODEX_USAGE_URL);const windows=codexQuotaWindowsFromUsage(usage,fetchedAt);if(!windows.length)throw new Error('额度接口未返回可识别的 5H / 7D 窗口');const usageCredits=normalizeCodexResetCredits(usage?.rate_limit_reset_credits??usage?.rateLimitResetCredits??null);let detailCredits={availableCount:null,applicableAvailableCount:null,credits:[],invalid:true},resetError='';try{detailCredits=normalizeCodexResetCredits(await codexManagementCall(account,'GET',CODEX_RESET_CREDITS_URL,{Accept:'application/json','OpenAI-Beta':'codex-1',Originator:'Codex Desktop'}));if(detailCredits.invalid)resetError='重置信息返回格式不可识别'}catch(error){resetError=error instanceof Error?error.message:'重置信息获取失败'}const credits=detailCredits.credits.length?detailCredits.credits:usageCredits.credits;const availableCount=detailCredits.availableCount??(credits.length?credits.length:null)??usageCredits.availableCount;const applicableAvailableCount=usageCredits.applicableAvailableCount??detailCredits.applicableAvailableCount??availableCount;return {status:'success',fetchedAt,windows,resetCredits:credits,resetAvailableCount:availableCount,resetApplicableCount:applicableAvailableCount,resetError}}
function createRedeemRequestId(){if(typeof crypto!=='undefined'&&typeof crypto.randomUUID==='function')return crypto.randomUUID();return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,char=>{const value=Math.floor(Math.random()*16),segment=char==='x'?value:(value&3)|8;return segment.toString(16)})}
function quotaTone(remaining){return remaining<=20?'danger':remaining<=50?'warn':'good'}
function quotaInfoHTML(state,authIndex){const key=escapeHTML(authIndex||'');if(!state)return '<button class="quota-action quota-refresh-one" type="button" data-auth-index="'+key+'">刷新额度</button>';if(state.status==='loading')return '<span class="quota-loading">刷新中…</span>';if(state.status==='error')return '<div class="quota-error-wrap"><span class="quota-error" title="'+escapeHTML(state.error||'')+'">刷新失败</span><button class="quota-action quota-refresh-one" type="button" data-auth-index="'+key+'">重试</button></div>';const observed=state.fetchedAt?dateText(state.fetchedAt):'';const rows=(state.windows||[]).map(window=>{const pct=Math.round(window.remaining),tone=quotaTone(window.remaining);return '<div class="quota-row"><span class="quota-label">'+escapeHTML(quotaDurationLabel(window.minutes))+'</span><span class="quota-bar"><span class="quota-bar-fill '+tone+'" style="width:'+Number(window.remaining).toFixed(2)+'%"></span></span><strong class="quota-pct">'+pct+'%</strong><span class="quota-reset">'+escapeHTML(shortDateText(window.resetAt))+'</span></div>'}).join('');return '<div class="quota-stack"'+(observed?' title="额度刷新于 '+escapeHTML(observed)+'"':'')+'>'+rows+'<div class="quota-card-actions"><button class="quota-action quota-refresh-one" type="button" data-auth-index="'+key+'">刷新</button></div></div>'}
function resetInfoHTML(state,authIndex){if(!state||state.status!=='success')return '';const key=escapeHTML(authIndex||''),credits=(state.resetCredits||[]).filter(item=>item&&item.expiresAtMs!==null).sort((a,b)=>a.expiresAtMs-b.expiresAtMs),count=state.resetApplicableCount??state.resetAvailableCount??(credits.length||null),canReset=Number(count||0)>0,isResetting=quotaResetting.has(normalizeAuthIndex(authIndex));let body='';if(credits.length)body='<div class="reset-stack">'+credits.map(item=>'<span>'+escapeHTML(shortDateText(item.expiresAtMs))+'</span>').join('')+'</div>';else if(count!==null)body='<span class="reset-count">可用 '+escapeHTML(String(count))+' 次</span>';else if(state.resetError)body='<span class="reset-error" title="'+escapeHTML(state.resetError)+'">获取失败</span>';if(canReset)body+='<div class="reset-actions"><button class="quota-action quota-reset-one" type="button" data-auth-index="'+key+'" '+(isResetting?'disabled':'')+'>'+(isResetting?'重置中…':'重置额度')+'</button></div>';return body}
function renderAccounts(accounts){currentAccounts=accounts.map(a=>({...a}));const excluded=excludedSet();for(const account of currentAccounts)account.selected=!excluded.has(accountSelectionKey(account));const selected=currentAccounts.filter(a=>a.selected).length;el('accountsMeta').textContent=currentAccounts.length+' 个 Codex 账号（已选择 '+selected+' 个；新账号默认生效）';el('summaryAccounts').textContent=selected+' 个';el('accounts').innerHTML=currentAccounts.length?currentAccounts.map(account=>{const email=account.email||'-',avatar=email==='-'?'?':email.trim().charAt(0),authIndex=normalizeAuthIndex(account.auth_index),quotaState=quotaStateForAccount(account);return '<tr><td class="select-cell"><input class="account-check" type="checkbox" data-key="'+escapeHTML(accountSelectionKey(account))+'" '+(account.selected?'checked':'')+' aria-label="'+escapeHTML(email)+' 生效"></td><td><div class="account"><span class="avatar">'+escapeHTML(avatar)+'</span><span class="account-email">'+escapeHTML(email)+'</span></div></td><td><span class="mono">'+escapeHTML(account.auth_index||'-')+'</span></td><td><span class="mono">'+escapeHTML(account.account_id||'-')+'</span></td><td>'+statusHTML(account)+cooldownHTML(account)+'</td><td class="quota-cell">'+quotaInfoHTML(quotaState,authIndex)+'</td><td class="reset-cell">'+resetInfoHTML(quotaState,authIndex)+'</td><td>'+httpHTML(account.http_status)+'</td><td>'+latencyText(account.latency_ms)+'</td><td class="date">'+dateText(account.checked_at)+'</td><td><span class="error" title="'+escapeHTML(account.error_message||'')+'">'+escapeHTML(account.error_message||'-')+'</span></td></tr>'}).join(''):emptyHTML(11,'没有 Codex 账号')}
function syncQuotaRefreshAllButton(){const button=el('quotaRefreshAll');if(!button)return;button.disabled=quotaRefreshAllRunning;button.classList.toggle('is-loading',quotaRefreshAllRunning);const label=button.querySelector('.quota-refresh-all-label');if(label)label.textContent=quotaRefreshAllRunning?'刷新中':'刷新全部额度'}
async function refreshQuotaForAccount(account,options={}){const silent=options.silent===true,key=normalizeAuthIndex(account?.auth_index);if(!key){if(!silent)showNotice('该账号缺少 auth_index，无法刷新额度',true);return false}if(quotaAccountDisabled(account)){if(!silent)showNotice('已停用账号不刷新额度',true);return false}if(quotaLoading.has(key))return null;quotaLoading.add(key);quotaCache.set(key,{status:'loading'});renderAccounts(currentAccounts);try{const state=await fetchCodexQuota(account);quotaCache.set(key,state);if(!silent)showNotice((account.email||key)+' 额度已刷新');return true}catch(error){quotaCache.set(key,{status:'error',error:error instanceof Error?error.message:'额度刷新失败'});if(!silent)handleActionError(error);return false}finally{quotaLoading.delete(key);renderAccounts(currentAccounts)}}
async function refreshAllQuotas(){if(quotaRefreshAllRunning)return;const targets=currentAccounts.filter(account=>normalizeAuthIndex(account.auth_index)&&!quotaAccountDisabled(account));if(!targets.length){showNotice('没有可刷新的 Codex 账号',true);return}quotaRefreshAllRunning=true;syncQuotaRefreshAllButton();let cursor=0,success=0,failed=0;const worker=async()=>{while(cursor<targets.length){const account=targets[cursor++],result=await refreshQuotaForAccount(account,{silent:true});if(result===true)success++;else if(result===false)failed++}};try{await Promise.all(Array.from({length:Math.min(4,targets.length)},worker));showNotice('额度刷新完成：成功 '+success+' 个'+(failed?'，失败 '+failed+' 个':''),failed>0&&success===0)}finally{quotaRefreshAllRunning=false;syncQuotaRefreshAllButton()}}
async function resetQuotaForAccount(account){const key=normalizeAuthIndex(account?.auth_index),state=quotaCache.get(key);if(!key||!state||state.status!=='success')return;const count=state.resetApplicableCount??state.resetAvailableCount??(state.resetCredits?.length||0);if(Number(count||0)<=0)return;if(quotaResetting.has(key))return;if(typeof window.confirm==='function'&&!window.confirm('确认消耗 1 次重置额度？此操作会立即重置当前 Codex 额度窗口。'))return;quotaResetting.add(key);renderAccounts(currentAccounts);try{await codexManagementCall(account,'POST',CODEX_RESET_CREDITS_CONSUME_URL,{},JSON.stringify({redeem_request_id:createRedeemRequestId()}));const refreshed=await fetchCodexQuota(account);quotaCache.set(key,refreshed);showNotice((account.email||key)+' 额度已重置')}catch(error){handleActionError(error)}finally{quotaResetting.delete(key);renderAccounts(currentAccounts)}}

function applyQuotaTableLayout(){const tbody=el('accounts'),table=tbody&&tbody.closest?tbody.closest('table'):null,headRow=table&&table.querySelector?table.querySelector('thead tr'):null;if(table)table.classList.add('accounts-quota-table');if(headRow&&!headRow.querySelector('[data-quota-column]')){const headers=[...headRow.querySelectorAll('th')],statusHeader=headers[4];if(statusHeader){const quotaHeader=document.createElement('th'),resetHeader=document.createElement('th');quotaHeader.textContent='额度信息';quotaHeader.dataset.quotaColumn='quota';resetHeader.textContent='重置信息';resetHeader.dataset.quotaColumn='reset';statusHeader.parentNode.insertBefore(quotaHeader,statusHeader.nextSibling);quotaHeader.parentNode.insertBefore(resetHeader,quotaHeader.nextSibling)}}const empty=tbody&&tbody.querySelector?tbody.querySelector('td.empty'):null;if(empty)empty.colSpan=11;const actions=document.querySelector('.accounts-card .actions');if(actions&&!el('quotaRefreshAll')){const button=document.createElement('button');button.id='quotaRefreshAll';button.type='button';button.className='button';button.innerHTML='<svg class="icon"><use href="#i-refresh"/></svg><span class="quota-refresh-all-label">刷新全部额度</span>';button.onclick=()=>void refreshAllQuotas();const refresh=el('refresh');if(refresh&&refresh.parentNode===actions)actions.insertBefore(button,refresh);else actions.appendChild(button)}if(!document.getElementById('quotaColumnStyles')){const style=document.createElement('style');style.id='quotaColumnStyles';style.textContent='.accounts-quota-table{min-width:1420px}.quota-cell{min-width:290px}.reset-cell{min-width:145px}.quota-stack{display:grid;gap:7px;min-width:270px}.quota-row{display:grid;grid-template-columns:28px minmax(82px,1fr) 38px 82px;gap:6px;align-items:center;white-space:nowrap}.quota-label{font:760 11px/1 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;color:#45566d}.quota-bar{height:7px;border-radius:999px;background:#e8edf3;overflow:hidden}.quota-bar-fill{display:block;height:100%;border-radius:inherit}.quota-bar-fill.good{background:#0ba66b}.quota-bar-fill.warn{background:#d69212}.quota-bar-fill.danger{background:#e43838}.quota-pct{font-size:11px;text-align:right}.quota-reset,.reset-stack,.reset-count,.reset-error,.quota-loading,.quota-error{font-size:11px;color:#607086}.reset-stack{display:grid;gap:4px;white-space:nowrap}.quota-card-actions,.reset-actions{margin-top:2px}.quota-action{min-height:26px;border:1px solid #cbd4df;border-radius:5px;background:#fff;padding:3px 8px;color:#526176;font-size:11px;font-weight:700;cursor:pointer}.quota-action:hover{background:#f8fafc}.quota-action:disabled{opacity:.55;cursor:not-allowed}.quota-error-wrap{display:flex;align-items:center;gap:7px}.quota-error{color:#c92525}.reset-error{color:#9b2e28}.accounts-quota-table th[data-quota-column="quota"]{min-width:290px}.accounts-quota-table th[data-quota-column="reset"]{min-width:145px}';document.head.appendChild(style)}syncQuotaRefreshAllButton()}
function syncWindowSaveState(){const button=el('saveWindow');if(button)button.disabled=!dirty}
function markDirty(){dirty=true;el('selectionDirty').classList.add('show');el('simDirty').classList.add('show');syncWindowSaveState()}
function clearDirty(){dirty=false;el('selectionDirty').classList.remove('show');el('simDirty').classList.remove('show');syncWindowSaveState()}
function renderSimulator(){const s=scheduleFromUI(true),ws=timeMin(s.work_start),ls=timeMin(s.lunch_start),le=timeMin(s.lunch_end),we=timeMin(s.work_end),anchor=timeMin(s.anchor_time),rec=recommendAnchorJS(s),work=(ls-ws)+(we-le),a=simulateAvailability(s,ws),b=simulateAvailability(s,anchor),gain=b-a,window=Number(s.window_hours)*60;el('workDuration').textContent=durationText(work);el('workDurationDetail').textContent=s.work_start+'–'+s.work_end+'，扣除午休 '+durationText(le-ls);el('strategyAMetric').textContent=durationText(a);el('strategyBMetric').textContent=durationText(b);el('gainMetric').textContent=(gain>=0?'+':'')+durationText(Math.abs(gain));el('strategyAValue').textContent=durationText(a);el('strategyBValue').textContent=durationText(b);el('strategyABar').style.width=Math.min(100,a/Math.max(work,1)*100)+'%';el('strategyBBar').style.width=Math.min(100,b/Math.max(work,1)*100)+'%';el('bestRange').textContent=clock(rec.start)+'–'+clock(rec.end);el('recommendedAnchor').textContent=clock(rec.recommended);const points=[];for(let p=anchor;p<we;p+=window)points.push(p);el('estimatedPoints').textContent='预计窗口点：'+points.map(clock).join(' / ')+'（每账号实际 +0–3 分钟）';el('windowStrip').innerHTML=points.map((p,i)=>'<div class="window-pill">窗口 '+(i+1)+'<br>'+escapeHTML(windowRangeText(p,p+window))+'</div>').join('');const start=0,end=1440;el('timelineAxis').innerHTML='';for(let h=0;h<=24;h++){const pos=h/24*100;el('timelineAxis').innerHTML+='<span class="axis-label" style="left:'+pos+'%">'+String(h).padStart(2,'0')+':00</span>'}renderTrack('trackA',s,ws,'a',start,end);renderTrack('trackB',s,anchor,'b',start,end);renderWindowSummary()}
async function persistSchedule(payload,message){const data=await api('/schedule',{method:'POST',body:JSON.stringify(payload)});savedSchedule=clone(data.schedule||payload);draftSchedule=clone(savedSchedule);scheduleData=data;el('nextRunFull').textContent=data.next_run_at?dateText(data.next_run_at):'未安排';clearDirty();showNotice(message);return data}
async function load(){if(loadInFlight)return;loadInFlight=true;syncQuotaCacheScope();clearTimeout(window.pollTimer);setConnection('');setButtonLoading(el('refresh'),true,null,'','','#i-refresh');try{const [status,accounts,history,schedule]=await Promise.all([api('/status'),api('/accounts'),api('/history'),api('/schedule')]);el('authOverlay').classList.remove('show');setConnection('online');const rows=accounts.accounts||[];pruneQuotaCache(rows);renderSchedule(schedule);renderAccounts(rows);renderHistory(history.history||[]);renderSimulator();setButtonLoading(el('run'),!!status.running,el('runLabel'),'检测中','立即检测','#i-play');if(status.running)window.pollTimer=setTimeout(load,1800)}catch(error){setConnection('offline');handleActionError(error)}finally{loadInFlight=false;setButtonLoading(el('refresh'),false,null,'','','#i-refresh')}}

document.querySelectorAll('input[name="scheduleMode"]').forEach(node=>node.addEventListener('change',()=>{toggleMode();markDirty()}));
el('accounts').addEventListener('change',event=>{if(event.target.classList.contains('account-check'))applySelectionFromDOM()});
el('accounts').addEventListener('click',event=>{const target=event.target.closest?event.target.closest('button[data-auth-index]'):null;if(!target)return;const account=accountByAuthIndex(target.dataset.authIndex);if(!account)return;if(target.classList.contains('quota-refresh-one'))void refreshQuotaForAccount(account);else if(target.classList.contains('quota-reset-one'))void resetQuotaForAccount(account)});
el('selectAll').addEventListener('click',()=>{document.querySelectorAll('.account-check').forEach(n=>n.checked=true);applySelectionFromDOM()});el('selectNone').addEventListener('click',()=>{document.querySelectorAll('.account-check').forEach(n=>n.checked=false);applySelectionFromDOM()});
el('refresh').addEventListener('click',load);el('historyPrev').addEventListener('click',()=>{historyPage--;renderHistoryPage()});el('historyNext').addEventListener('click',()=>{historyPage++;renderHistoryPage()});el('historyPageSize').addEventListener('change',()=>{historyPageSize=Number(el('historyPageSize').value);historyPage=1;renderHistoryPage()});
async function runNow(){setButtonLoading(el('run'),true,el('runLabel'),'检测中','立即检测','#i-play');try{await api('/run',{method:'POST',body:'{}'});showNotice('检测已启动');await load()}catch(error){handleActionError(error)}finally{setButtonLoading(el('run'),false,el('runLabel'),'检测中','立即检测','#i-play')}}el('run').addEventListener('click',runNow);el('scheduleRun').addEventListener('click',runNow);
el('scheduleForm').addEventListener('submit',async event=>{event.preventDefault();const payload=scheduleFromUI(false);el('saveSchedule').disabled=true;try{const data=await persistSchedule(payload,'检测计划已保存');renderSchedule(data);renderAccounts(currentAccounts);renderSimulator()}catch(error){handleActionError(error)}finally{el('saveSchedule').disabled=false}});
const simulatorInputChanged=()=>{markDirty();renderSimulator()};for(const id of ['windowHours','quotaMinutes','workStart','lunchStart','lunchEnd','workEnd','simTimezone','healthThreshold','anchorTime']){const node=el(id);node.addEventListener('input',simulatorInputChanged);node.addEventListener('change',simulatorInputChanged)}document.querySelectorAll('#weekdayToggles input').forEach(n=>n.addEventListener('change',()=>{markDirty();renderSimulator()}));
el('recalculate').addEventListener('click',()=>{const s=scheduleFromUI(true),rec=recommendAnchorJS(s);el('anchorTime').value=clock(rec.recommended);markDirty();renderSimulator()});
el('undoChanges').addEventListener('click',()=>{draftSchedule=clone(savedSchedule);renderAccounts(currentAccounts.map(a=>({...a})));fillSimulator(draftSchedule);const radio=document.querySelector('input[name="scheduleMode"][value="'+(draftSchedule.schedule_mode||'window_optimized')+'"]');if(radio)radio.checked=true;el('intervalMin').value=draftSchedule.interval_min||30;el('dailyTimes').value=draftSchedule.daily_times||'';el('timezone').value=draftSchedule.timezone||'Asia/Shanghai';el('timeoutSec').value=draftSchedule.timeout_sec||30;toggleMode();clearDirty();showNotice('已撤销未保存修改')});
el('saveWindow').addEventListener('click',async()=>{const payload=scheduleFromUI(true);const radio=document.querySelector('input[name="scheduleMode"][value="window_optimized"]');if(radio)radio.checked=true;toggleMode();el('saveWindow').disabled=true;try{const data=await persistSchedule(payload,'窗口优化配置已保存并生效');renderSchedule(data);renderAccounts(currentAccounts);renderSimulator()}catch(error){handleActionError(error)}finally{el('saveWindow').disabled=!dirty}});
el('timezone').addEventListener('input',()=>{if(selectedMode()==='window_optimized'){el('simTimezone').value=el('timezone').value;markDirty();renderSimulator()}});
el('authForm').addEventListener('submit',event=>{event.preventDefault();const key=el('adminKey').value.trim();if(!key)return;sessionStorage.setItem(SESSION_KEY,key);el('adminKey').value='';load()});
applyQuotaTableLayout();applyFullWidthLayout();clearDirty();load();
